# golangci-lint configuration
# Docs: https://golangci-lint.run/usage/configuration/
# Run: golangci-lint run ./...

version: "2"

linters:
  enable:
    - errcheck # Check that errors are handled
    - gosimple # Simplify code
    - govet # Go vet checks
    - ineffassign # Detect ineffectual assignments
    - staticcheck # Static analysis (SA class rules)
    - unused # Detect unused code
    - bodyclose # Check that HTTP response bodies are closed
    - noctx # Detect HTTP calls without a context
    - contextcheck # Check that context is properly propagated

  settings:
    errcheck:
      # Ignore errors from fmt.Print* family and json.Encoder.Encode
      exclude-functions:
        - fmt.Print
        - fmt.Println
        - fmt.Printf
        - fmt.Fprintln
        - (encoding/json.Encoder).Encode
    govet:
      enable-all: true

  exclusions:
    rules:
      # Allow unhandled errors in test files
      - path: _test\.go
        linters:
          - errcheck
      # Allow unused parameters named _ in interface implementations
      - text: "parameter '_' seems to be unused"
        linters:
          - unparam

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
