// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: tracker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{0}
}

type MoveCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// Target status — must be a valid ApplicationStatus string.
	// Valid values: TO_APPLY, APPLIED, INTERVIEW, OFFER, REJECTED, HIRED
	NewStatus     string `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveCardRequest) Reset() {
	*x = MoveCardRequest{}
	mi := &file_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCardRequest) ProtoMessage() {}

func (x *MoveCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCardRequest.ProtoReflect.Descriptor instead.
func (*MoveCardRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *MoveCardRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *MoveCardRequest) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

type AddNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNoteRequest) Reset() {
	*x = AddNoteRequest{}
	mi := &file_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNoteRequest) ProtoMessage() {}

func (x *AddNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNoteRequest.ProtoReflect.Descriptor instead.
func (*AddNoteRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *AddNoteRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *AddNoteRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type RateApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"` // 1–5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateApplicationRequest) Reset() {
	*x = RateApplicationRequest{}
	mi := &file_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateApplicationRequest) ProtoMessage() {}

func (x *RateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateApplicationRequest.ProtoReflect.Descriptor instead.
func (*RateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *RateApplicationRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *RateApplicationRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type ListApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*ApplicationProto    `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_tracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{4}
}

func (x *ListApplicationsResponse) GetApplications() []*ApplicationProto {
	if x != nil {
		return x.Applications
	}
	return nil
}

// ApplicationProto mirrors the Applications table row returned to clients.
// JSON blobs (ai_analysis, history_log) are carried as raw bytes so the
// Gateway can forward them to the frontend without an extra parse/marshal cycle.
type ApplicationProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentStatus string                 `protobuf:"bytes,2,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"`
	// Raw JSON bytes — forwarded as-is to GraphQL clients.
	AiAnalysis []byte `protobuf:"bytes,3,opt,name=ai_analysis,json=aiAnalysis,proto3" json:"ai_analysis,omitempty"`
	HistoryLog []byte `protobuf:"bytes,7,opt,name=history_log,json=historyLog,proto3" json:"history_log,omitempty"`
	// Nullable string fields (empty string = NULL in DB)
	GeneratedCoverLetter string `protobuf:"bytes,4,opt,name=generated_cover_letter,json=generatedCoverLetter,proto3" json:"generated_cover_letter,omitempty"`
	UserNotes            string `protobuf:"bytes,5,opt,name=user_notes,json=userNotes,proto3" json:"user_notes,omitempty"`
	// Nullable int32 — 0 means unrated
	UserRating    int32                  `protobuf:"varint,6,opt,name=user_rating,json=userRating,proto3" json:"user_rating,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationProto) Reset() {
	*x = ApplicationProto{}
	mi := &file_tracker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationProto) ProtoMessage() {}

func (x *ApplicationProto) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationProto.ProtoReflect.Descriptor instead.
func (*ApplicationProto) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{5}
}

func (x *ApplicationProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplicationProto) GetCurrentStatus() string {
	if x != nil {
		return x.CurrentStatus
	}
	return ""
}

func (x *ApplicationProto) GetAiAnalysis() []byte {
	if x != nil {
		return x.AiAnalysis
	}
	return nil
}

func (x *ApplicationProto) GetHistoryLog() []byte {
	if x != nil {
		return x.HistoryLog
	}
	return nil
}

func (x *ApplicationProto) GetGeneratedCoverLetter() string {
	if x != nil {
		return x.GeneratedCoverLetter
	}
	return ""
}

func (x *ApplicationProto) GetUserNotes() string {
	if x != nil {
		return x.UserNotes
	}
	return ""
}

func (x *ApplicationProto) GetUserRating() int32 {
	if x != nil {
		return x.UserRating
	}
	return 0
}

func (x *ApplicationProto) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ApplicationProto) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_tracker_proto protoreflect.FileDescriptor

const file_tracker_proto_rawDesc = "" +
	"\n" +
	"\rtracker.proto\x12\atracker\x1a\x1fgoogle/protobuf/timestamp.proto\"\x19\n" +
	"\x17ListApplicationsRequest\"W\n" +
	"\x0fMoveCardRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x1d\n" +
	"\n" +
	"new_status\x18\x02 \x01(\tR\tnewStatus\"K\n" +
	"\x0eAddNoteRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\"W\n" +
	"\x16RateApplicationRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\"Y\n" +
	"\x18ListApplicationsResponse\x12=\n" +
	"\fapplications\x18\x01 \x03(\v2\x19.tracker.ApplicationProtoR\fapplications\"\xf7\x02\n" +
	"\x10ApplicationProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0ecurrent_status\x18\x02 \x01(\tR\rcurrentStatus\x12\x1f\n" +
	"\vai_analysis\x18\x03 \x01(\fR\n" +
	"aiAnalysis\x12\x1f\n" +
	"\vhistory_log\x18\a \x01(\fR\n" +
	"historyLog\x124\n" +
	"\x16generated_cover_letter\x18\x04 \x01(\tR\x14generatedCoverLetter\x12\x1d\n" +
	"\n" +
	"user_notes\x18\x05 \x01(\tR\tuserNotes\x12\x1f\n" +
	"\vuser_rating\x18\x06 \x01(\x05R\n" +
	"userRating\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xb8\x02\n" +
	"\x0eTrackerService\x12W\n" +
	"\x10ListApplications\x12 .tracker.ListApplicationsRequest\x1a!.tracker.ListApplicationsResponse\x12?\n" +
	"\bMoveCard\x12\x18.tracker.MoveCardRequest\x1a\x19.tracker.ApplicationProto\x12=\n" +
	"\aAddNote\x12\x17.tracker.AddNoteRequest\x1a\x19.tracker.ApplicationProto\x12M\n" +
	"\x0fRateApplication\x12\x1f.tracker.RateApplicationRequest\x1a\x19.tracker.ApplicationProtoB(Z&jobmate/tracker-service/internal/pb;pbb\x06proto3"

var (
	file_tracker_proto_rawDescOnce sync.Once
	file_tracker_proto_rawDescData []byte
)

func file_tracker_proto_rawDescGZIP() []byte {
	file_tracker_proto_rawDescOnce.Do(func() {
		file_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)))
	})
	return file_tracker_proto_rawDescData
}

var file_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tracker_proto_goTypes = []any{
	(*ListApplicationsRequest)(nil),  // 0: tracker.ListApplicationsRequest
	(*MoveCardRequest)(nil),          // 1: tracker.MoveCardRequest
	(*AddNoteRequest)(nil),           // 2: tracker.AddNoteRequest
	(*RateApplicationRequest)(nil),   // 3: tracker.RateApplicationRequest
	(*ListApplicationsResponse)(nil), // 4: tracker.ListApplicationsResponse
	(*ApplicationProto)(nil),         // 5: tracker.ApplicationProto
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
}
var file_tracker_proto_depIdxs = []int32{
	5, // 0: tracker.ListApplicationsResponse.applications:type_name -> tracker.ApplicationProto
	6, // 1: tracker.ApplicationProto.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: tracker.ApplicationProto.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: tracker.TrackerService.ListApplications:input_type -> tracker.ListApplicationsRequest
	1, // 4: tracker.TrackerService.MoveCard:input_type -> tracker.MoveCardRequest
	2, // 5: tracker.TrackerService.AddNote:input_type -> tracker.AddNoteRequest
	3, // 6: tracker.TrackerService.RateApplication:input_type -> tracker.RateApplicationRequest
	4, // 7: tracker.TrackerService.ListApplications:output_type -> tracker.ListApplicationsResponse
	5, // 8: tracker.TrackerService.MoveCard:output_type -> tracker.ApplicationProto
	5, // 9: tracker.TrackerService.AddNote:output_type -> tracker.ApplicationProto
	5, // 10: tracker.TrackerService.RateApplication:output_type -> tracker.ApplicationProto
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tracker_proto_init() }
func file_tracker_proto_init() {
	if File_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracker_proto_goTypes,
		DependencyIndexes: file_tracker_proto_depIdxs,
		MessageInfos:      file_tracker_proto_msgTypes,
	}.Build()
	File_tracker_proto = out.File
	file_tracker_proto_goTypes = nil
	file_tracker_proto_depIdxs = nil
}
