// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: tracker.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrackerService_ListApplications_FullMethodName = "/tracker.TrackerService/ListApplications"
	TrackerService_MoveCard_FullMethodName         = "/tracker.TrackerService/MoveCard"
	TrackerService_AddNote_FullMethodName          = "/tracker.TrackerService/AddNote"
	TrackerService_RateApplication_FullMethodName  = "/tracker.TrackerService/RateApplication"
)

// TrackerServiceClient is the client API for TrackerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─────────────────────────────────────────────────────────────────────────────
// TrackerService — Kanban CRM for job applications
//
// All RPCs require the caller to pass the authenticated user's ID via gRPC
// metadata key "x-user-id". The Gateway injects this after JWT validation.
// ─────────────────────────────────────────────────────────────────────────────
type TrackerServiceClient interface {
	// List all applications for the authenticated user.
	ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...grpc.CallOption) (*ListApplicationsResponse, error)
	// Move a Kanban card to a new status (state machine validated).
	MoveCard(ctx context.Context, in *MoveCardRequest, opts ...grpc.CallOption) (*ApplicationProto, error)
	// Add or update the free-text note on an application.
	AddNote(ctx context.Context, in *AddNoteRequest, opts ...grpc.CallOption) (*ApplicationProto, error)
	// Set a 1–5 star rating on an application.
	RateApplication(ctx context.Context, in *RateApplicationRequest, opts ...grpc.CallOption) (*ApplicationProto, error)
}

type trackerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackerServiceClient(cc grpc.ClientConnInterface) TrackerServiceClient {
	return &trackerServiceClient{cc}
}

func (c *trackerServiceClient) ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...grpc.CallOption) (*ListApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApplicationsResponse)
	err := c.cc.Invoke(ctx, TrackerService_ListApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerServiceClient) MoveCard(ctx context.Context, in *MoveCardRequest, opts ...grpc.CallOption) (*ApplicationProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationProto)
	err := c.cc.Invoke(ctx, TrackerService_MoveCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerServiceClient) AddNote(ctx context.Context, in *AddNoteRequest, opts ...grpc.CallOption) (*ApplicationProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationProto)
	err := c.cc.Invoke(ctx, TrackerService_AddNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerServiceClient) RateApplication(ctx context.Context, in *RateApplicationRequest, opts ...grpc.CallOption) (*ApplicationProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationProto)
	err := c.cc.Invoke(ctx, TrackerService_RateApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackerServiceServer is the server API for TrackerService service.
// All implementations must embed UnimplementedTrackerServiceServer
// for forward compatibility.
//
// ─────────────────────────────────────────────────────────────────────────────
// TrackerService — Kanban CRM for job applications
//
// All RPCs require the caller to pass the authenticated user's ID via gRPC
// metadata key "x-user-id". The Gateway injects this after JWT validation.
// ─────────────────────────────────────────────────────────────────────────────
type TrackerServiceServer interface {
	// List all applications for the authenticated user.
	ListApplications(context.Context, *ListApplicationsRequest) (*ListApplicationsResponse, error)
	// Move a Kanban card to a new status (state machine validated).
	MoveCard(context.Context, *MoveCardRequest) (*ApplicationProto, error)
	// Add or update the free-text note on an application.
	AddNote(context.Context, *AddNoteRequest) (*ApplicationProto, error)
	// Set a 1–5 star rating on an application.
	RateApplication(context.Context, *RateApplicationRequest) (*ApplicationProto, error)
	mustEmbedUnimplementedTrackerServiceServer()
}

// UnimplementedTrackerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackerServiceServer struct{}

func (UnimplementedTrackerServiceServer) ListApplications(context.Context, *ListApplicationsRequest) (*ListApplicationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApplications not implemented")
}
func (UnimplementedTrackerServiceServer) MoveCard(context.Context, *MoveCardRequest) (*ApplicationProto, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveCard not implemented")
}
func (UnimplementedTrackerServiceServer) AddNote(context.Context, *AddNoteRequest) (*ApplicationProto, error) {
	return nil, status.Error(codes.Unimplemented, "method AddNote not implemented")
}
func (UnimplementedTrackerServiceServer) RateApplication(context.Context, *RateApplicationRequest) (*ApplicationProto, error) {
	return nil, status.Error(codes.Unimplemented, "method RateApplication not implemented")
}
func (UnimplementedTrackerServiceServer) mustEmbedUnimplementedTrackerServiceServer() {}
func (UnimplementedTrackerServiceServer) testEmbeddedByValue()                        {}

// UnsafeTrackerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackerServiceServer will
// result in compilation errors.
type UnsafeTrackerServiceServer interface {
	mustEmbedUnimplementedTrackerServiceServer()
}

func RegisterTrackerServiceServer(s grpc.ServiceRegistrar, srv TrackerServiceServer) {
	// If the following call panics, it indicates UnimplementedTrackerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackerService_ServiceDesc, srv)
}

func _TrackerService_ListApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).ListApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_ListApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).ListApplications(ctx, req.(*ListApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackerService_MoveCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).MoveCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_MoveCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).MoveCard(ctx, req.(*MoveCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackerService_AddNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).AddNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_AddNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).AddNote(ctx, req.(*AddNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackerService_RateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).RateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_RateApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).RateApplication(ctx, req.(*RateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackerService_ServiceDesc is the grpc.ServiceDesc for TrackerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracker.TrackerService",
	HandlerType: (*TrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListApplications",
			Handler:    _TrackerService_ListApplications_Handler,
		},
		{
			MethodName: "MoveCard",
			Handler:    _TrackerService_MoveCard_Handler,
		},
		{
			MethodName: "AddNote",
			Handler:    _TrackerService_AddNote_Handler,
		},
		{
			MethodName: "RateApplication",
			Handler:    _TrackerService_RateApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tracker.proto",
}
